In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("MovieGenre.csv", encoding="ISO-8859-1")

In [4]:
df

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...
40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island (1980),4.3,Drama,https://images-na.ssl-images-amazon.com/images...
40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana (1981),4.7,Comedy,https://images-na.ssl-images-amazon.com/images...
40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison (2006),4.5,Horror,https://images-na.ssl-images-amazon.com/images...
40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da (1979),6.5,Action|Comedy,https://images-na.ssl-images-amazon.com/images...
40107,70710,http://www.imdb.com/title/tt70710,Snatched (1973),6.5,Crime|Drama|Thriller,NaN

In [5]:
df

,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.3,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.9,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.6,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.7,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.9,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...
40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island (1980),4.3,Drama,https://images-na.ssl-images-amazon.com/images...
40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana (1981),4.7,Comedy,https://images-na.ssl-images-amazon.com/images...
40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison (2006),4.5,Horror,https://images-na.ssl-images-amazon.com/images...
40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da (1979),6.5,Action|Comedy,https://images-na.ssl-images-amazon.com/images...
40107,70710,http://www.imdb.com/title/tt70710,Snatched (1973),6.5,Crime|Drama|Thriller,NaN

In [6]:
pip install nltk

Requirement already satisfied: nltk in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\sr inithya\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

In [8]:
from nltk.corpus import stopwords

In [9]:
nltk.download('punkt')  
nltk.download('punkt_tab') 
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\SR
[nltk_data]     INITHYA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
import re

In [11]:
cleaned = []

In [12]:
for text in df['Title']:  
    cleaned_text = re.sub(r'[^\w\s]', '', text) 
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  
    cleaned_data = cleaned_text.strip() 
    cleaned.append(cleaned_data)

In [13]:
tokens = [word_tokenize(x) for x in cleaned]

In [14]:
stop = set(stopwords.words('english'))

In [15]:
stpktn = []

In [16]:
for k in range(len(df['Title'])):  
    p = [i for i in tokens[k] if i not in stop]  
    stpktn.append(p)

In [17]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [18]:
stemed_data = []
for Text in stpktn:
  stm = [ps.stem(word) for word in Text]
  stemed_data.append(stm)

In [19]:
stemed_data

[['toy', 'stori', '1995'],
 ['jumanji', '1995'],
 ['grumpier', 'old', 'men', '1995'],
 ['wait', 'exhal', '1995'],
 ['father', 'bride', 'part', 'ii', '1995'],
 ['heat', '1995'],
 ['sabrina', '1995'],
 ['tom', 'huck', '1995'],
 ['sudden', 'death', '1995'],
 ['goldeney', '1995'],
 ['the', 'american', 'presid', '1995'],
 ['dracula', 'dead', 'love', 'it', '1995'],
 ['balto', '1995'],
 ['nixon', '1995'],
 ['cutthroat', 'island', '1995'],
 ['casino', '1995'],
 ['sens', 'sensibl', '1995'],
 ['four', 'room', '1995'],
 ['ace', 'ventura', 'when', 'natur', 'call', '1995'],
 ['money', 'train', '1995'],
 ['get', 'shorti', '1995'],
 ['copycat', '1995'],
 ['assassin', '1995'],
 ['powder', '1995'],
 ['leav', 'la', 'vega', '1995'],
 ['othello', '1995'],
 ['now', 'then', '1995'],
 ['persuas'],
 ['the', 'citi', 'lost', 'children', '1995'],
 ['yao', 'yao', 'yao', 'dao', 'wai', 'po', 'qiao', '1995'],
 ['danger', 'mind', '1995'],
 ['twelv', 'monkey', '1995'],
 ['wing', 'courag', '1995'],
 ['babe', '1995'],
 ['carrington', '1995'],
 ['dead', 'man', 'walk', '1995'],
 ['across', 'sea', 'time', '1995'],
 ['it', 'take', 'two', '1995'],
 ['clueless', '1995'],
 ['cri', 'belov', 'countri', '1995'],
 ['richard', 'iii', '1995'],
 ['dead', 'presid', '1995'],
 ['restor', '1995'],
 ['mortal', 'kombat', '1995'],
 ['to', 'die', 'for', '1995'],
 ['how', 'make', 'american', 'quilt', '1995'],
 ['se7en', '1995'],
 ['pocahonta', '1995'],
 ['when', 'night', 'is', 'fall', '1995'],
 ['the', 'usual', 'suspect', '1995'],
 ['guardian', 'angel', '1994'],
 ['mighti', 'aphrodit', '1995'],
 ['lamerica', '1994'],
 ['the', 'big', 'green', '1995'],
 ['georgia', '1995'],
 ['kid', 'round', 'tabl', '1995'],
 ['home', 'holiday', '1995'],
 ['il', 'postino', 'the', 'postman', '1994'],
 ['le', 'confessionn', '1995'],
 ['the', 'indian', 'cupboard', '1995'],
 ['eye', 'eye', '1996'],
 ['mr', 'holland', 'opu', '1995'],
 ['dont',
  'be',
  'menac',
  'south',
  'central',
  'while',
  'drink',
  'your',
  'juic',
  'hood',
  '1996'],
 ['two', 'if', 'sea', '1996'],
 ['biodom', '1996'],
 ['lawnmow', 'man', '2', 'beyond', 'cyberspac', '1996'],
 ['two', 'bit', '1995'],
 ['french', 'twist', '1995'],
 ['friday', '1995'],
 ['from', 'dusk', 'till', 'dawn', '1996'],
 ['fair', 'game', '1995'],
 ['kick', 'scream', '1995'],
 ['le', 'misírabl', '1995'],
 ['bed', 'rose', '1996'],
 ['big', 'bulli', '1996'],
 ['screamer', '1995'],
 ['nico', 'icon', '1995'],
 ['the', 'cross', 'guard', '1995'],
 ['the', 'juror', '1996'],
 ['the', 'white', 'balloon', '1995'],
 ['thing', 'do', 'denver', 'when', 'your', 'dead', '1995'],
 ['antonia', 'line', '1995'],
 ['onc', 'upon', 'time', 'when', 'we', 'were', 'color', '1995'],
 ['last', 'summer', 'hampton', '1995'],
 ['angel', 'insect', '1995'],
 ['white', 'squall', '1996'],
 ['dunston', 'check', 'in', '1996'],
 ['black', 'sheep', '1996'],
 ['nick', 'time', '1995'],
 ['the', 'journey', 'august', 'king', '1995'],
 ['mari', 'reilli', '1996'],
 ['vampir', 'brooklyn', '1995'],
 ['beauti', 'girl', '1996'],
 ['broken', 'arrow', '1996'],
 ['a', 'midwint', 'tale', '1995'],
 ['la', 'hain', '1995'],
 ['shop', '1994'],
 ['heidi', 'fleiss', 'hollywood', 'madam', '1995'],
 ['citi', 'hall', '1996'],
 ['bottl', 'rocket', '1996'],
 ['mr', 'wrong', '1996'],
 ['unforgett', '1996'],
 ['happi', 'gilmor', '1996'],
 ['the', 'bridg', 'madison', 'counti', '1995'],
 ['nobodi', 'love', 'me', '1994'],
 ['muppet', 'treasur', 'island', '1996'],
 ['catwalk', '1995'],
 ['headless', 'bodi', 'topless', 'bar', '1995'],
 ['braveheart', '1995'],
 ['taxi', 'driver', '1976'],
 ['rumbl', 'bronx', '1995'],
 ['befor', 'after', '1996'],
 ['margaret', 'museum', '1995'],
 ['happi', 'is', 'field', '1995'],
 ['ann', 'frank', 'rememb', '1995'],
 ['the', 'young', 'poison', 'handbook', '1995'],
 ['if', 'luci', 'fell', '1996'],
 ['steal', 'big', 'steal', 'littl', '1995'],
 ['race', 'sun', '1996'],
 ['the', 'boy', 'st', 'vincent', '1992'],
 ['boomerang', '1992'],
 ['chungk', 'express', '1994'],
 ['the', 'star', 'maker', '1995'],
 ['flirt', 'disast', '1996'],
 ['the', 'neverend', 'stori', 'iii', '1994'],
 ['the', 'silenc', 'palac', '1994'],
 ['jupit', 'wife', '1995'],
 ['pie', 'ski', '1996'],
 ['angela', '1995'],
 ['franki', 'starlight', '1995'],
 ['jade', '1995'],
 ['nueba', 'yol', '1995'],
 ['sonic', 'outlaw', '1995'],
 ['down', 'periscop', '1996'],
 ['from', 'journal', 'jean', 'seberg', '1995'],
 ['man', 'year', '1995'],
 ['the', 'neon', 'bibl', '1995'],
 ['target', '1995'],
 ['up', 'close', 'person', '1996'],
 ['the', 'birdcag', '1996'],
 ['cieni', '1988'],
 ['gospa', '1995'],
 ['the', 'brother', 'mcmullen', '1995'],
 ['bad', 'boy', '1995'],
 ['the', 'amaz', 'panda', 'adventur', '1995'],
 ['the', 'basketbal', 'diari', '1995'],
 ['an', 'aw', 'big', 'adventur', '1995'],
 ['amateur', '1994'],
 ['apollo', '13', '1995'],
 ['rob', 'roy', '1995'],
 ['the', 'addict', '1995'],
 ['batman', 'forev', '1995'],
 ['bell', 'de', 'jour', '1967'],
 ['beyond', 'rangoon', '1995'],
 ['blue', 'face', '1995'],
 ['canadian', 'bacon', '1995'],
 ['casper', '1995'],
 ['clocker', '1995'],
 ['congo', '1995'],
 ['crimson', 'tide', '1995'],
 ['crumb', '1994'],
 ['desperado', '1995'],
 ['devil', 'blue', 'dress', '1995'],
 ['die', 'hard', 'vengeanc', '1995'],
 ['the', 'doom', 'gener', '1995'],
 ['feast', 'juli', '1995'],
 ['first', 'knight', '1995'],
 ['free', 'willi', '2', 'the', 'adventur', 'home', '1995'],
 ['hacker', '1995'],
 ['jeffrey', '1995'],
 ['johnni', 'mnemon', '1995'],
 ['judg', 'dredd', '1995'],
 ['juri', 'duti', '1995'],
 ['kid', '1995'],
 ['live', 'oblivion', '1995'],
 ['lord', 'illus', '1995'],
 ['love', 'human', 'remain', '1993'],
 ['mad', 'love', '1995'],
 ['mallrat', '1995'],
 ['mighti', 'morphin', 'power', 'ranger', 'the', 'movi', '1995'],
 ['moonlight', 'valentino', '1995'],
 ['mute', 'wit', '1995'],
 ['nadja', '1994'],
 ['the', 'net', '1995'],
 ['nine', 'month', '1995'],
 ['parti', 'girl', '1995'],
 ['the', 'propheci', '1995'],
 ['reckless', '1995'],
 ['safe', '1995'],
 ['the', 'scarlet', 'letter', '1995'],
 ['the', 'show', '1995'],
 ['showgirl', '1995'],
 ['smoke', '1995'],
 ['someth', 'talk', 'about', '1995'],
 ['speci', '1995'],
 ['the', 'star', 'fell', 'henrietta', '1995'],
 ['strang', 'day', '1995'],
 ['the', 'umbrella', 'cherbourg', '1964'],
 ['the', 'tie', 'that', 'bind', '1995'],
 ['three', 'wish', '1995'],
 ['total', 'eclips', '1995'],
 ['to', 'wong', 'foo', 'thank', 'everyth', 'juli', 'newmar', '1995'],
 ['under', 'sieg', '2', 'dark', 'territori', '1995'],
 ['unstrung', 'hero', '1995'],
 ['unzip', '1995'],
 ['a', 'walk', 'cloud', '1995'],
 ['waterworld', '1995'],
 ['white', 'man', 'burden', '1995'],
 ['wild', 'bill', '1995'],
 ['the', 'brown', 'version', '1994'],
 ['bushwhack', '1995'],
 ['burnt', 'sun', '1994'],
 ['befor', 'rain', '1994'],
 ['befor', 'sunris', '1995'],
 ['billi', 'madison', '1995'],
 ['the', 'babysitt', '1995'],
 ['boy', 'side', '1995'],
 ['the', 'cure', '1995'],
 ['castl', 'freak', '1995'],
 ['circl', 'friend', '1995'],
 ['clerk', '1994'],
 ['don', 'juan', 'demarco', '1994'],
 ['disclosur', '1994'],
 ['dream', 'man', '1995'],
 ['drop', 'zone', '1994'],
 ['destini', 'turn', 'radio', '1995'],
 ['death', 'maiden', '1994'],
 ['dolor', 'claiborn', '1995'],
 ['dumb', 'dumber', '1994'],
 ['eat', 'drink', 'man', 'woman', '1994'],
 ['exotica', '1994'],
 ['exit', 'eden', '1994'],
 ['ed', 'wood', '1994'],
 ['french', 'kiss', '1995'],
 ['forget', 'pari', '1995'],
 ['far', 'home', 'the', 'adventur', 'yellow', 'dog', '1995'],
 ['a', 'goofi', 'movi', '1995'],
 ['hideaway', '1995'],
 ['fluke', '1995'],
 ['farinelli', '1994'],
 ['gordi', '1995'],
 ['gumbi', 'the', 'movi', '1995'],
 ['the', 'glass', 'shield', '1994'],
 ['hoop', 'dream', '1994'],
 ['heavenli', 'creatur', '1994'],
 ['houseguest', '1995'],
 ['immort', 'belov', '1994'],
 ['heavi', 'weight', '1995'],
 ['the', 'hunt', '1995'],
 ['iq', '1994'],
 ['interview', 'vampir', 'the', 'vampir', 'chronicl', '1994'],
 ['jefferson', 'pari', '1995'],
 ['the', 'jerki', 'boy', '1995'],
 ['junior', '1994'],
 ['just', 'caus', '1995'],
 ['a', 'kid', 'king', 'arthur', 'court', '1995'],
 ['kiss', 'death', '1995'],
 ['star', 'war', 'episod', 'iv', 'a', 'new', 'hope', '1977'],
 ['littl', 'women', '1994'],
 ['a', 'littl', 'princess', '1995'],
 ['ladybird', 'ladybird', '1994'],
 ['lenfer', '1994'],
 ['como', 'agua', 'para', 'chocol', '1992'],
 ['legend', 'fall', '1994'],
 ['major', 'payn', '1995'],
 ['littl', 'odessa', '1994'],
 ['mi', 'vida', 'loca', '1993'],
 ['love', 'affair', '1994'],
 ['lose', 'isaiah', '1995'],
 ['the', 'mad', 'king', 'georg', '1994'],
 ['mari', 'shelley', 'frankenstein', '1994'],
 ['man', 'hous', '1995'],
 ['mix', 'nut', '1994'],
 ['milk', 'money', '1994'],
 ['miracl', '34th', 'street', '1994'],
 ['miami', 'rhapsodi', '1995'],
 ['my', 'famili', '1995'],
 ['murder', 'first', '1995'],
 ['nobodi', 'fool', '1994'],
 ['nell', '1994'],
 ['new', 'jersey', 'drive', '1995'],
 ['new', 'york', 'cop', '1993'],
 ['beyond', 'bedlam', '1994'],
 ['nemesi', '2', 'nebula', '1995'],
 ['nina', 'take', 'lover', '1994'],
 ['natur', 'born', 'killer', '1994'],
 ['onli', 'you', '1994'],
 ['onc', 'were', 'warrior', '1994'],
 ['poison', 'ivi', 'ii', '1996'],
 ['outbreak', '1995'],
 ['líon', 'the', 'profession', '1994'],
 ['the', 'perez', 'famili', '1995'],
 ['a', 'pyromaniac', 'love', 'stori', '1995'],
 ['pulp', 'fiction', '1994'],
 ['panther', '1995'],
 ['tui', 'shou', '1992'],
 ['priest', '1994'],
 ['quiz', 'show', '1994'],
 ['pictur', 'bride', '1994'],
 ['queen', 'margot', '1994'],
 ['the', 'quick', 'dead', '1995'],
 ['roommat', '1995'],
 ['readi', 'wear', '1994'],
 ['three', 'color', 'red', '1994'],
 ['three', 'color', 'blue', '1993'],
 ['three', 'color', 'white', '1994'],
 ['pao', 'da', 'shuang', 'deng', '1994'],
 ['rentakid', '1995'],
 ['rel', 'fear', '1994'],
 ['stuart', 'save', 'hi', 'famili', '1995'],
 ['the', 'swan', 'princess', '1994'],
 ['the', 'secret', 'roan', 'inish', '1994'],
 ['the', 'specialist', '1994'],
 ['stargat', '1994'],
 ['the', 'santa', 'claus', '1994'],
 ['the', 'shawshank', 'redempt', '1994'],
 ['shallow', 'grave', '1994'],
 ['sutur', '1993'],
 ['strawberri', 'chocol', '1993'],
 ['swim', 'shark', '1994'],
 ['the', 'sum', 'us', '1994'],
 ['senior', 'trip', '1995'],
 ['to', 'live', '1994'],
 ['tank', 'girl', '1995'],
 ['tale', 'crypt', 'demon', 'knight', '1995'],
 ['star', 'trek', 'gener', '1994'],
 ['tale', 'hood', '1995'],
 ['tom', 'viv', '1994'],
 ['villag', 'damn', '1995'],
 ['tommi', 'boy', '1995'],
 ['vanya', '42nd', 'street', '1994'],
 ['the', 'underneath', '1995'],
 ['the', 'walk', 'dead', '1995'],
 ['what', 'eat', 'gilbert', 'grape', '1993'],
 ['virtuos', '1995'],
 ['while', 'you', 'were', 'sleep', '1995'],
 ['the', 'war', '1994'],
 ['doubl', 'happi', '1994'],
 ['muriel', 'wed', '1994'],
 ['the', 'babysitt', 'club', '1995'],
 ['ace', 'ventura', 'pet', 'detect', '1994'],
 ['the', 'adventur', 'priscilla', 'queen', 'desert', '1994'],
 ['backbeat', '1994'],
 ['bitter', 'moon', '1992'],
 ['bullet', 'over', 'broadway', '1994'],
 ['clear', 'present', 'danger', '1994'],
 ['the', 'client', '1994'],
 ['corrina', 'corrina', '1994'],
 ['crooklyn', '1994'],
 ['the', 'crow', '1994'],
 ['cobb', '1994'],
 ['the', 'flintston', '1994'],
 ['forrest', 'gump', '1994'],
 ['four', 'wed', 'funer', '1994'],
 ['higher', 'learn', '1995'],
 ['i', 'like', 'it', 'like', 'that', '1994'],
 ['i', 'love', 'troubl', '1994'],
 ['it', 'could', 'happen', 'you', '1994'],
 ['the', 'jungl', 'book', '1994'],
 ['die', 'macht', 'der', 'bilder', 'leni', 'riefenstahl', '1993'],
 ['the', 'lion', 'king', '1994'],
 ['littl', 'buddha', '1993'],
 ['new', 'nightmar', '1994'],
 ['the', 'mask', '1994'],
 ['maverick', '1994'],
 ['mr', 'parker', 'viciou', 'circl', '1994'],
 ['nake', 'gun', '33', '13', 'the', 'final', 'insult', '1994'],
 ['the', 'paper', '1994'],
 ['realiti', 'bite', '1994'],
 ['red', 'rock', 'west', '1993'],
 ['rihi', 'rih', '1994'],
 ['safe', 'passag', '1994'],
 ['the', 'river', 'wild', '1994'],
 ['speed', '1994'],
 ['speechless', '1994'],
 ['timecop', '1994'],
 ['true', 'lie', '1994'],
 ['when', 'man', 'love', 'woman', '1994'],
 ['wolf', '1994'],
 ['wyatt', 'earp', '1994'],
 ['bad', 'compani', '1995'],
 ['a', 'man', 'no', 'import', '1994'],
 ['sfw', '1994'],
 ['a', 'low', 'down', 'dirti', 'shame', '1994'],
 ['boy', 'life', 'three', 'stori', 'love', 'lust', 'liber', '1994'],
 ['colonel', 'chabert', '1994'],
 ['faster', 'pussycat', 'kill', 'kill', '1965'],
 ['jason', 'lyric', '1994'],
 ['the', 'secret', 'adventur', 'tom', 'thumb', '1993'],
 ['street', 'fighter', '1994'],
 ['coldblood', '1995'],
 ['desert', 'wind', '1994'],
 ['fall', 'time', '1995'],
 ['the', 'fear', '1995'],
 ['frank', 'olli', '1995'],
 ['girl', 'cadillac', '1995'],
 ['homag', '1995'],
 ['mirag', '1995'],
 ['open', 'season', '1995'],
 ['do', 'crí_mene', '1994'],
 ['brother', 'minist', 'the', 'assassin', 'malcolm', 'x', '1994'],
 ['highland', 'the', 'final', 'dimens', '1994'],
 ['feder', 'hill', '1994'],
 ['in', 'mouth', 'mad', '1994'],
 ['8', 'second', '1994'],
 ['abov', 'rim', '1994'],
 ['addam', 'famili', 'valu', '1993'],
 ['martin', 'lawrenc', 'you', 'so', 'crazi', '1994'],
 ['the', 'age', 'innoc', '1993'],
 ['airhead', '1994'],
 ['the', 'air', 'up', 'there', '1994'],
 ['anoth', 'stakeout', '1993'],
 ['bad', 'girl', '1994'],
 ['barcelona', '1994'],
 ['be', 'human', '1994'],
 ['the', 'beverli', 'hillbilli', '1993'],
 ['beverli', 'hill', 'cop', 'iii', '1994'],
 ['black', 'beauti', '1994'],
 ['blink', '1993'],
 ['blown', 'away', '1994'],
 ['blue', 'chip', '1994'],
 ['blue', 'ski', '1994'],
 ['bodi', 'snatcher', '1993'],
 ['box', 'helena', '1993'],
 ['a', 'bronx', 'tale', '1993'],
 ['cabin', 'boy', '1994'],
 ['calendar', 'girl', '1993'],
 ['carlito', 'way', '1993'],
 ['citi', 'slicker', 'ii', 'the', 'legend', 'curli', 'gold', '1994'],
 ['clean', 'slate', '1994'],
 ['cliffhang', '1993'],
 ['conehead', '1993'],
 ['color', 'night', '1994'],
 ['cop', 'robberson', '1994'],
 ['the', 'cowboy', 'way', '1994'],
 ['danger', 'game', '1993'],
 ['dave', '1993'],
 ['daze', 'confus', '1993'],
 ['demolit', 'man', '1993'],
 ['the', 'endless', 'summer', '2', '1994'],
 ['even', 'cowgirl', 'get', 'blue', '1993'],
 ['fatal', 'instinct', '1993'],
 ['farewel', 'my', 'concubin', '1993'],
 ['the', 'favor', '1994'],
 ['fearless', '1993'],
 ['fear', 'black', 'hat', '1993'],
 ['with', 'honor', '1994'],
 ['flesh', 'bone', '1993'],
 ['widow', 'peak', '1994'],
 ['for', 'love', 'money', '1993'],
 ['the', 'firm', '1993'],
 ['free', 'willi', '1993'],
 ['fresh', '1994'],
 ['the', 'fugit', '1993'],
 ['geronimo', 'an', 'american', 'legend', '1993'],
 ['the', 'getaway', '1994'],
 ['get', 'even', 'dad', '1994'],
 ['go', 'fish', '1994'],
 ['a', 'good', 'man', 'africa', '1994'],
 ['guilti', 'sin', '1993'],
 ['hard', 'target', '1993'],
 ['heaven', 'earth', '1993'],
 ['hot', 'shot', 'part', 'deux', '1993'],
 ['live', 'nude', 'girl', '1995'],
 ['the',
  'englishman',
  'who',
  'went',
  'up',
  'hill',
  'but',
  'came',
  'down',
  'mountain',
  '1995'],
 ['the', 'hous', 'spirit', '1993'],
 ['hous', 'parti', '3', '1994'],
 ['the', 'hudsuck', 'proxi', '1994'],
 ['ill', 'do', 'anyth', '1994'],
 ['in', 'armi', 'now', '1994'],
 ['in', 'line', 'fire', '1993'],
 ['in', 'name', 'father', '1993'],
 ['the', 'inkwel', '1994'],
 ['what', 'love', 'got', 'do', 'it', '1993'],
 ['jimmi', 'hollywood', '1994'],
 ['judgment', 'night', '1993'],
 ['jurass', 'park', '1993'],
 ['kalifornia', '1993'],
 ['kill', 'zoe', '1993'],
 ['king', 'hill', '1993'],
 ['lassi', '1994'],
 ['last', 'action', 'hero', '1993'],
 ['life', 'mikey', '1993'],
 ['lightn', 'jack', '1994'],
 ['m', 'butterfli', '1993'],
 ['made', 'america', '1993'],
 ['malic', '1993'],
 ['the', 'man', 'without', 'face', '1993'],
 ['manhattan', 'murder', 'mysteri', '1993'],
 ['menac', 'ii', 'societi', '1993'],
 ['execut', 'decis', '1996'],
 ['in', 'realm', 'sens', '1976'],
 ['what', 'happen', 'wa', '1994'],
 ['much', 'ado', 'about', 'noth', '1993'],
 ['mr', 'jone', '1993'],
 ['mr', 'wonder', '1993'],
 ['mr', 'doubtfir', '1993'],
 ['nake', '1993'],
 ['the', 'next', 'karat', 'kid', '1994'],
 ['the', 'new', 'age', '1994'],
 ['no', 'escap', '1994'],
 ['north', '1994'],
 ['orlando', '1992'],
 ['a', 'perfect', 'world', '1993'],
 ['philadelphia', '1993'],
 ['the', 'piano', '1993'],
 ['poetic', 'justic', '1993'],
 ['the', 'program', '1993'],
 ['the', 'puppet', 'master', '1994'],
 ['radioland', 'murder', '1994'],
 ['the', 'ref', '1994'],
 ['the', 'remain', 'day', '1993'],
 ['renaiss', 'man', '1994'],
 ['rise', 'sun', '1993'],
 ['the', 'road', 'wellvil', '1994'],
 ['robocop', '3', '1993'],
 ['robin', 'hood', 'men', 'tight', '1993'],
 ['romeo', 'is', 'bleed', '1993'],
 ['romper', 'stomper', '1992'],
 ['rubi', 'paradis', '1993'],
 ['rudi', '1993'],
 ['the', 'saint', 'fort', 'washington', '1993'],
 ['le', 'nuit', 'fauv', '1992'],
 ['schindler', 'list', '1993'],
 ['the', 'scout', '1994'],
 ['search', 'bobbi', 'fischer', '1993'],
 ['second', 'best', '1994'],
 ['the', 'secret', 'garden', '1993'],
 ['serial', 'mom', '1994'],
 ['the', 'shadow', '1994'],
 ['shadowland', '1993'],
 ['short', 'cut', '1993'],
 ['a', 'simpl', 'twist', 'fate', '1994'],
 ['siren', '1993'],
 ['six', 'degre', 'separ', '1993'],
 ['sleepless', 'seattl', '1993'],
 ['sliver', '1993'],
 ['blade', 'runner', '1982'],
 ['son', 'law', '1993'],
 ['so', 'i', 'marri', 'axe', 'murder', '1993'],
 ['strike', 'distanc', '1993'],
 ['harem', '1985'],
 ['super', 'mario', 'bro', '1993'],
 ['surviv', 'game', '1994'],
 ['termin', 'veloc', '1994'],
 ['thirti', 'two', 'short', 'film', 'about', 'glenn', 'gould', '1993'],
 ['threesom', '1994'],
 ['the', 'nightmar', 'befor', 'christma', '1993'],
 ['the', 'three', 'musket', '1993'],
 ['tombston', '1993'],
 ['trial', 'juri', '1994'],
 ['true', 'romanc', '1993'],
 ['the', 'war', 'room', '1993'],
 ['the', 'pagemast', '1994'],
 ['pari', 'franc', '1993'],
 ['the', 'bean', 'egypt', 'main', '1994'],
 ['killer', '1994'],
 ['welcom', 'dollhous', '1995'],
 ['germin', '1993'],
 ['chaser', '1994'],
 ['crono', '1993'],
 ['nake', 'new', 'york', '1993'],
 ['kika', '1993'],
 ['bhaji', 'beach', '1993'],
 ['littl', 'big', 'leagu', '1994'],
 ['the', 'slingshot', '1993'],
 ['wideey', 'legless'],
 ['foreign', 'student', '1994'],
 ['ciao', 'professor', '1992'],
 ['spank', 'monkey', '1994'],
 ['the', 'littl', 'rascal', '1994'],
 ['íó', 'la', 'mode', '1993'],
 ['andr', '1994'],
 ['la', 'scorta', '1993'],
 ['princess', 'caraboo', '1994'],
 ['the', 'celluloid', 'closet', '1995'],
 ['cafí', 'au', 'lait', '1993'],
 ['caro', 'diario', '1993'],
 ['i', 'dont', 'want', 'talk', 'about', 'it', '1993'],
 ['the', 'bradi', 'bunch', 'movi', '1995'],
 ['home', 'alon', '1990'],
 ['ghost', '1990'],
 ['aladdin', '1992'],
 ['termin', '2', 'judgment', 'day', '1991'],
 ['danc', 'wolv', '1990'],
 ['tough', 'deadli', '1995'],
 ['batman', '1989'],
 ['the', 'silenc', 'lamb', '1991'],
 ['snow', 'white', 'seven', 'dwarf', '1937'],
 ['beauti', 'beast', '1991'],
 ['pinocchio', '1940'],
 ['pretti', 'woman', '1990'],
 ['window', 'pari', '1993'],
 ['the', 'wild', 'bunch', '1969'],
 ['love', '45', '1994'],
 ['wu', 'kui', '1994'],
 ['a', 'great', 'day', 'harlem', '1994'],
 ['bye', 'bye', 'love', '1995'],
 ['crimin', '1997'],
 ['one', 'fine', 'day', '1996'],
 ['candyman', 'farewel', 'flesh', '1995'],
 ['centuri', '1993'],
 ['fargo', '1996'],
 ['homeward', 'bound', 'ii', 'lost', 'san', 'francisco', '1996'],
 ['heavi', 'metal', '1981'],
 ['hellrais', 'bloodlin', '1996'],
 ['the', 'pallbear', '1996'],
 ['jane', 'eyr', '1996'],
 ['load', '1994'],
 ['bread', 'chocol', '1974'],
 ['the', 'aristocat', '1970'],
 ['the', 'flower', 'my', 'secret', '1995'],
 ['two', 'much', '1996'],
 ['ed', '1996'],
 ['cerro', 'torr', 'schrei', 'au', 'stein', '1991'],
 ['ma', 'saison', 'prífíríe', '1993'],
 ['a', 'modern', 'affair', '1995'],
 ['condit', 'red', '1995'],
 ['halfaouin', 'boy', 'terrac', '1990'],
 ['a', 'thin', 'line', 'between', 'love', 'hate', '1996'],
 ['the', 'last', 'supper', '1995'],

In [20]:
stm=[" ".join(i) for i in stemed_data]

In [21]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: scikit-learn in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sr inithya\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cv=CountVectorizer(max_features=2000)

In [24]:
vc=cv.fit(stm)

In [25]:
import pickle
with open("vectorizer.pickle","wb") as vcfile:
    pickle.dump(vc,vcfile)

In [26]:
x=vc.transform(stm).toarray()

In [27]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(40108, 2000))

In [28]:
y=df["Genre"]

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
mb=MultinomialNB()

In [31]:
import pickle
with open("model.pickle","wb") as model_file:
    pickle.dump(mb,model_file)